steps:
  - name: node:14
    entrypoint: npm
    args: ["install"]
  - name: node:14
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy --app=app.yaml",
      ]
timeout: 1600
